### ISSUE TITLE
can't see the params for j.core.identity.new

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#359]
because it's using *args, **kwags, please let's have it more explicit

**Comment by waleedhammam** [comment]
fixed by merging https://github.com/threefoldtech/js-ng/pull/265

**Comment by siddiquagig** [comment]
Verified

![image](https://user-images.githubusercontent.com/25789724/85944659-9e6e4780-b949-11ea-9400-fb43bcf7903e.png)

**Comment by abom** [comment]
@siddiquagig How it's verified? what's meant by params here is the `docstring` related params in the lower pane, as [the previous comment](https://github.com/threefoldtech/js-ng/issues/359#issuecomment-648121844) of @waleedhammam.

**Comment by siddiquagig** [comment]
@abom  you are right , the lower panel for documentation for this function is still not visible

**Comment by abom** [comment]
@siddiquagig Please try again now after merging the new loader.

**Comment by siddiquagig** [comment]
@abom , its ok now:

![image](https://user-images.githubusercontent.com/25789724/85948825-f1ed8f00-b963-11ea-9ed7-890c29565ad5.png)
